### ISSUE TITLE
Create Character panic runtime error

### ISSUE THREAD

**Issue by njdaniel** [njdaniel/dnd#16]
**Describe the bug**
2021/09/29 11:29:12 character init() called
2021/09/29 11:29:12 Current dir: /home/nick/dev/github.com/njdaniel/dnd
2021/09/29 11:29:12 [background/body_type.txt background/complexion.txt background/drawbacks.txt background/dwarf-female-height.txt background/dwarf-female-weight.csv background/dwarf-male-height.txt background/dwarf-male-weight.csv background/elf-female-height.txt background/elf-female-weight.csv background/elf-male-height.txt background/elf-male-weight.csv background/eyecolor.csv background/haircolor.csv background/human-female-height.txt background/human-female-weight.csv background/human-male-height.txt background/human-male-weight.csv background/marks.txt background/season.txt background/socialclass.txt background/upbringing.txt equipment/martial_melee_weapons.js equipment/martial_range_weapons.js equipment/simple_melee_weapons.js equipment/simple_range_weapons.js names/dwarf-female.txt names/dwarf-male.txt names/elf-female.txt names/elf-male.txt names/human-female.txt names/human-male.txt prayers/allfather.json prayers/god-emperor.json prayers/holy-mother.json prayers/lord-death.json prayers/stag-god.json prayers/the-old-one.json prayers/wolf-king.json professions/archtypes/archtypes.txt professions/archtypes/commoner/artisan.txt professions/archtypes/commoner/barbersurgeon.txt professions/archtypes/doctor.json professions/archtypes/engineer.json professions/archtypes/ranger/animaltamer.txt professions/archtypes/ranger/bountyhunter.txt professions/archtypes/ranger/trapper.txt professions/archtypes/rogue/burglar.txt professions/archtypes/scholar/apothecary.txt professions/archtypes/scholar/diabolist.txt professions/archtypes/scholar/engineer.txt professions/archtypes/sellsword.json professions/archtypes/socialite/cultist.txt professions/archtypes/socialite/doomsayer.txt professions/archtypes/socialite/entertainer.txt professions/archtypes/trapper.json professions/archtypes/warrior/dragoon.txt professions/archtypes/warrior/sellsword/advances-bonuses.txt professions/archtypes/warrior/sellsword/advances-skills.txt professions/archtypes/warrior/sellsword/profession-trait.txt professions/archtypes/warrior/sellsword/sellsword-advances.txt professions/archtypes/warrior/sellsword/sellsword-description.txt professions/archtypes/warrior/sellsword/starting-equip.csv professions/archtypes/warrior/sellsword/starting-money.txt professions/archtypes/warrior/sellsword/talents.txt professions/archtypes/warrior/slayer.txt professions/bulklist.txt professions/types/agriculture.txt professions/types/arts.txt professions/types/business-trade.txt professions/types/communications.txt professions/types/construction.txt professions/types/craftman.txt professions/types/crime.txt professions/types/government.txt professions/types/health.txt professions/types/labor.txt professions/types/magic.txt professions/types/military.txt professions/types/outcast.txt professions/types/religion.txt professions/types/scholars.txt professions/types/transportation.txt professions/wages.js services/tavern1.txt services/tavern2.txt spells/animism.json spells/astromancy.json spells/elementalism.json spells/luminescene.json spells/necromancy.json spells/pyromancy.json spells/shadowmancy.json spells/sorcery.json traits/talent-badaxe.txt traits/talents1.txt traits/talents10.txt traits/talents11.txt traits/talents2.txt traits/talents3.txt traits/talents4.txt traits/talents5.txt traits/talents6.txt traits/talents7.txt traits/talents8.txt traits/talents9.txt traits/talents_overview.txt traits/traits.json]
2021/09/29 11:29:12 character init() done
creating character
**panic: runtime error: index out of range [2] with length 2**

goroutine 1 [running]:
github.com/njdaniel/dnd/services/commands/character.Gender.String(...)
        /home/nick/dev/github.com/njdaniel/dnd/services/commands/character/create.go:60
github.com/njdaniel/dnd/services/commands/character.createGender(...)
        /home/nick/dev/github.com/njdaniel/dnd/services/commands/character/factory.go:10
github.com/njdaniel/dnd/services/commands/character.NewCharacter(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/nick/dev/github.com/njdaniel/dnd/services/commands/character/create.go:355 +0x3aea
github.com/njdaniel/dnd/cmd.glob..func2(0xf88ac0, 0xfbe730, 0x0, 0x0)
        /home/nick/dev/github.com/njdaniel/dnd/cmd/create.go:38 +0x37
github.com/spf13/cobra.(*Command).execute(0xf88ac0, 0xfbe730, 0x0, 0x0, 0xf88ac0, 0xfbe730)
        /home/nick/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xf897e0, 0x443a1a, 0xf46680, 0xc000000180)
        /home/nick/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/nick/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/njdaniel/dnd/cmd.Execute()
        /home/nick/dev/github.com/njdaniel/dnd/cmd/root.go:45 +0x31
main.main()
        /home/nick/dev/github.com/njdaniel/dnd/main.go:20 +0x20

**To Reproduce**
    ./dnd character create

**Expected behavior**
json return of new character

**Comment by njdaniel** [comment]
need to update error printing, need to print with more info. Also logging might be helpful. What would be the difference from printing to term screen and logging? Would the logging go to a file? With timestamp? How many log files?
